In [18]:
# Check codebook

import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None) 

owid_codebook = pd.read_csv(r"C:\Users\eirad\Desktop\IT ACADEMY\Sprint_13_Proyecto_Final\data\owid-energy-codebook.csv")

owid_codebook.head()

,column,title,description,unit,source
0,country,Country,Geographic location.,NaN,Our World in Data - Regions (2025)
1,year,Year,Year of observation.,NaN,Our World in Data - Regions (2025)
2,iso_code,ISO code,ISO 3166-1 alpha-3 three-letter country codes.,NaN,International Organization for Standardization - Regions (2023)
3,population,Population,"Population by country, available from 10,000 BCE to 2100, based on data and estimates from different sources.",people,Population based on various sources (2024) [https://ourworldindata.org/population-sources]
4,gdp,Gross domestic product (GDP),Total economic output of a country or region per year. This data is adjusted for inflation and differences in living costs between countries.,international-$ in 2011 prices ($),Bolt and van Zanden – Maddison Project Database 2023 [https://www.rug.nl/ggdc/historicaldevelopment/maddison/releases/maddison-project-database-2023]

In [19]:
gdp = owid_codebook[owid_codebook["column"].str.contains("gdp", case=False)]
gdp

,column,title,description,unit,source
4,gdp,Gross domestic product (GDP),Total economic output of a country or region per year. This data is adjusted for inflation and differences in living costs between countries.,international-$ in 2011 prices ($),Bolt and van Zanden – Maddison Project Database 2023 [https://www.rug.nl/ggdc/historicaldevelopment/maddison/releases/maddison-project-database-2023]
33,energy_per_gdp,Primary energy consumption per GDP,Measured in kilowatt-hours per international-$.,kilowatt-hours per $ (kWh),U.S. Energy Information Administration - International Energy Data (2025) [https://www.eia.gov/opendata/bulkfiles.php]; Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]; Bolt and van Zanden – Maddison Project Database 2023 [https://www.rug.nl/ggdc/historicaldevelopment/maddison/releases/maddison-project-database-2023]

In [ ]:
# consumption

consumption = owid_codebook[owid_codebook["column"].str.contains("consumption", case=False)]
consumption

,column,title,description,unit,source
8,biofuel_consumption,Primary energy consumption from biofuels,Measured in terawatt-hours.,terawatt-hours (TWh),Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
17,coal_consumption,Primary energy consumption from coal,Measured in terawatt-hours.,terawatt-hours (TWh),Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
39,fossil_fuel_consumption,Primary energy consumption from fossil fuels,Measured in terawatt-hours.,terawatt-hours (TWh),Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
44,gas_consumption,Primary energy consumption from gas,Measured in terawatt-hours.,terawatt-hours (TWh),Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
57,hydro_consumption,Primary energy consumption from hydropower,"Measured in terawatt-hours, using the substitution method.",terawatt-hours (TWh),Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
65,low_carbon_consumption,Primary energy consumption from low-carbon sources,"Measured in terawatt-hours, using the substitution method.",terawatt-hours (TWh),Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
75,nuclear_consumption,Primary energy consumption from nuclear power,"Measured in terawatt-hours, using the substitution method.",terawatt-hours (TWh),Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
83,oil_consumption,Primary energy consumption from oil,Measured in terawatt-hours.,terawatt-hours (TWh),Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
93,other_renewable_consumption,Primary energy consumption from other renewables,"Measured in terawatt-hours, using the substitution method.",terawatt-hours (TWh),Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
105,primary_energy_consumption,Primary energy consumption,Measured in terawatt-hours.,terawatt-hours (TWh),U.S. Energy Information Administration - International Energy Data (2025) [https://www.eia.gov/opendata/bulkfiles.php]; Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
108,renewables_consumption,Primary energy consumption from renewables,"Measured in terawatt-hours, using the substitution method.",terawatt-hours (TWh),Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
116,solar_consumption,Primary energy consumption from solar power,"Measured in terawatt-hours, using the substitution method.",terawatt-hours (TWh),Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
124,wind_consumption,Primary energy consumption from wind power,"Measured in terawatt-hours, using the substitution method.",terawatt-hours (TWh),Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]

In [22]:
share_energy = owid_codebook[owid_codebook["column"].str.contains("share_energy",case=False)]
share_energy

,column,title,description,unit,source
12,biofuel_share_energy,Share of primary energy consumption that comes from biofuels,"Measured as a percentage of the total primary energy, using the substitution method.",%,Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
25,coal_share_energy,Share of primary energy consumption that comes from coal,"Measured as a percentage of the total primary energy, using the substitution method.",%,Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
29,electricity_share_energy,Total electricity generation as share of primary energy,"Measured as a percentage of total, direct primary energy consumption in the country or region.",%,Ember - Yearly Electricity Data Europe (2026) [https://ember-energy.org/data/yearly-electricity-data/]; Ember - Yearly Electricity Data (2026) [https://ember-energy.org/data/yearly-electricity-data/]; Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
41,fossil_share_energy,Share of primary energy consumption that comes from fossil fuels,"Measured as a percentage of the total primary energy, using the substitution method.",%,Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
53,gas_share_energy,Share of primary energy consumption that comes from gas,"Measured as a percentage of the total primary energy, using the substitution method.",%,Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
62,hydro_share_energy,Share of primary energy consumption that comes from hydropower,"Measured as a percentage of the total primary energy, using the substitution method.",%,Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
70,low_carbon_share_energy,Share of primary energy consumption that comes from low-carbon sources,"Measured as a percentage of the total primary energy, using the substitution method.",%,Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
80,nuclear_share_energy,Share of primary energy consumption that comes from nuclear power,"Measured as a percentage of the total primary energy, using the substitution method.",%,Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
92,oil_share_energy,Share of primary energy consumption that comes from oil,"Measured as a percentage of the total primary energy, using the substitution method.",%,Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
103,other_renewables_share_energy,Share of primary energy consumption that comes from other renewables,"Measured as a percentage of the total primary energy, using the substitution method.",%,Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
113,renewables_share_energy,Share of primary energy consumption that comes from renewables,"Measured as a percentage of the total primary energy, using the substitution method.",%,Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
121,solar_share_energy,Share of primary energy consumption that comes from solar power,"Measured as a percentage of the total primary energy, using the substitution method.",%,Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]
129,wind_share_energy,Share of primary energy consumption that comes from wind power,"Measured as a percentage of the total primary energy, using the substitution method.",%,Energy Institute - Statistical Review of World Energy (2025) [https://www.energyinst.org/statistical-review/]

In [23]:
#

share_energy = owid_codebook[owid_codebook["column"].str.contains("emis",case=False)]
share_energy

,column,title,description,unit,source
54,greenhouse_gas_emissions,Lifecycle emissions from electricity generation,Measured in megatonnes of CO₂ equivalents.,million tonnes CO₂ equivalents (Mt),Ember - Yearly Electricity Data Europe (2026) [https://ember-energy.org/data/yearly-electricity-data/]; Ember - Yearly Electricity Data (2026) [https://ember-energy.org/data/yearly-electricity-data/]